# Generated by Django 4.1.3 on 2023-06-27 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plant_disease", "0002_countrycity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="diseases", old_name="plant_name", new_name="plant",
        ),
    ]
