# Generated by Django 4.1.3 on 2023-06-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plant_disease", "0003_rename_plant_name_diseases_plant"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plants",
            fields=[
                ("plants_id", models.AutoField(primary_key=True, serialize=False)),
                ("plants_name", models.CharField(max_length=60)),
            ],
        ),
    ]
