# Generated by Django 4.1.3 on 2023-06-28 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "plant_disease",
            "0010_city2_country2_news2_countrycity2_city2_country_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="City3",
            fields=[
                ("city_id", models.AutoField(primary_key=True, serialize=False)),
                ("city_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Country3",
            fields=[
                ("country_id", models.AutoField(primary_key=True, serialize=False)),
                ("country_name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Plants2",
            fields=[
                ("plants_id", models.AutoField(primary_key=True, serialize=False)),
                ("plants_name", models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name="Plants3",
            fields=[
                ("plants_id", models.AutoField(primary_key=True, serialize=False)),
                ("plants_name", models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name="news3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="photos")),
                ("time", models.DateField()),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plant_disease.diseases",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plant_disease.city3",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plant_disease.country3",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plant_disease.plants3",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CountryCity3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plant_disease.city3",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plant_disease.country3",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="city3",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="plant_disease.country3"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="city3", unique_together={("city_name", "country")},
        ),
    ]
