# Generated by Django 4.1.3 on 2023-06-28 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "plant_disease",
            "0011_city3_country3_plants2_plants3_news3_countrycity3_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="City4",
            fields=[
                ("city_id", models.AutoField(primary_key=True, serialize=False)),
                ("city_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Country4",
            fields=[
                ("country_id", models.AutoField(primary_key=True, serialize=False)),
                ("country_name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Plants4",
            fields=[
                ("plants_id", models.AutoField(primary_key=True, serialize=False)),
                ("plants_name", models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name="news4",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="photos")),
                ("time", models.DateField()),
                ("plant", models.CharField(max_length=100)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plant_disease.diseases",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plant_disease.city4",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plant_disease.country4",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CountryCity4",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plant_disease.city4",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plant_disease.country4",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="city4",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="plant_disease.country4"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="city4", unique_together={("city_name", "country")},
        ),
    ]
