# Generated by Django 4.1.3 on 2023-08-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plant_disease", "0012_city4_country4_plants4_news4_countrycity4_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
            ],
        ),
    ]
