# Generated by Django 4.1.3 on 2023-08-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plant_disease", "0013_mymedia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mymedia",
            name="image",
            field=models.ImageField(upload_to="photos"),
        ),
    ]
